try to locate asdf bin

diff --git a/asdf-install-plugins b/asdf-install-plugins
--- a/asdf-install-plugins
+++ b/asdf-install-plugins
@@ -4,6 +4,13 @@ if [ ! -f .tool-versions ]; then
   exit 1
 fi
 
+ASDF = $(which asdf)
+if [ -z "$ASDF" ]; then
+  echo "asdf not found!"
+  exit 1
+fi
+echo "using asdf located in $ASDF"
+
 cat .tool-versions | awk '{print $1}' | while read -r plugin; do
   if [ -z "$plugin" ]; then
     continue
@@ -14,7 +21,7 @@ cat .tool-versions | awk '{print $1}' | while read -r plugin; do
     echo "$plugin is already installed. Skipping"
   else
     echo "Installing $plugin"
-    asdf plugin-add $plugin
+    $ASDF plugin-add $plugin
     ex=$?
     if [ $ex -eq 2 ] || [ $ex -eq 0 ]; then
       echo "Successfully installed $plugin"
diff --git a/asdf-install-versions b/asdf-install-versions
--- a/asdf-install-versions
+++ b/asdf-install-versions
@@ -4,6 +4,13 @@ if [ ! -f .tool-versions ]; then
   exit 1
 fi
 
+ASDF = $(which asdf || echo "/root/.asdf/bin/asdf")
+if [ -z "$ASDF" ]; then
+  echo "asdf not found!"
+  exit 1
+fi
+echo "using asdf located in $ASDF"
+
 cat .tool-versions | while read -r version; do
   if [ -z "$version" ]; then
     continue
@@ -13,10 +20,10 @@ cat .tool-versions | while read -r version; do
   ex=$?
   if [ $ex -eq 0 ]; then
     echo "$version is already installed. Reshimming"
-    asdf reshim $version
+    $ASDF reshim $version
   else
     echo "$version is not installed. Trying to install..."
-    asdf install $version
+    $ASDF install $version
     ex=$?
     if [ $ex -ne 0 ]; then
       echo "Error installing $version"
