wip

diff --git a/asdf-install-plugins b/asdf-install-plugins
--- a/asdf-install-plugins
+++ b/asdf-install-plugins
@@ -4,17 +4,24 @@ if [ ! -f .tool-versions ]; then
   exit 1
 fi
 
+ASDF = "/root/.asdf/bin/asdf"
+if [ -f "$ASDF" ]; then
+  echo "asdf not found!"
+  exit 1
+fi
+echo using asdf located in "$ASDF"
+
 cat .tool-versions | awk '{print $1}' | while read -r plugin; do
   if [ -z "$plugin" ]; then
     continue
   fi
 
-  ret=$(asdf plugin-list | grep $plugin)
+  ret=$($ASDF plugin-list | grep $plugin)
   if [ $? -eq 0 ]; then
     echo "$plugin is already installed. Skipping"
   else
     echo "Installing $plugin"
-    /root/.asdf/bin/asdf plugin-add $plugin
+    $ASDF plugin-add $plugin
     ex=$?
     if [ $ex -eq 2 ] || [ $ex -eq 0 ]; then
       echo "Successfully installed $plugin"
diff --git a/asdf-install-versions b/asdf-install-versions
--- a/asdf-install-versions
+++ b/asdf-install-versions
@@ -4,16 +4,23 @@ if [ ! -f .tool-versions ]; then
   exit 1
 fi
 
+ASDF = "/root/.asdf/bin/asdf"
+if [ -f "$ASDF" ]; then
+  echo "asdf not found!"
+  exit 1
+fi
+echo using asdf located in "$ASDF"
+
 cat .tool-versions | while read -r version; do
   if [ -z "$version" ]; then
     continue
   fi
 
-  ret=$(/root/.asdf/bin/asdf where $version)
+  ret=$($ASDF where $version)
   ex=$?
   if [ $ex -eq 0 ]; then
     echo "$version is already installed. Reshimming"
-    /root/.asdf/bin/asdf reshim $version
+    $ASDF reshim $version
   else
     echo "$version is not installed. Trying to install..."
     $ASDF install $version
